### PR TITLE
fix: error handling cors

### LINKED ISSUE #16: TypeError: Failed to fetch
Hey,

I'm running into this error while rendering some buttons from popular Frames.

Examples:
Frame: https://fc-polls.vercel.app/polls/87b1ed3f-5f86-479a-acc7-727943eecfe3
Repo: https://github.com/farcasterxyz/fc-polls or https://github.com/xmtp-labs/fc-polls
Button: `Create your poll`

Frame: 
Repo: https://github.com/fabriguespe/a-frame-in-100-lines-main
Frame: https://a-frame-in-100-lines-main.vercel.app/
Buttons: `All`

Live domain
CleanShot 2024-03-17 at 15 26 19@2x

Localhost:
CleanShot 2024-03-15 at 18 17 05@2x

Environment:
- Client: https://dev-inbox.vercel.app/
- Repo: https://github.com/xmtp/dev-inbox.git

### PR DESCRIPTION
**Pull request by stephancill**
Updates error handling to handle errors in async functions and returns CORS headers in error responses.

Fixes #16

### CODE REVIEW

**Review by alexrisch — APPROVED** [review]

File: packages/server/src/index.ts [hunk 1]
```diff
@@ -12,27 +12,27 @@ export async function handleRequest(req: Request): Promise<Response> {
 		const path = getRequestPath(req);
 		if (req.method === 'GET') {
 			if (path === '/media') {
-				return handleMedia(req);
+				return await handleMedia(req);
```
Comment (neekolas) [inline packages/server/src/index.ts:15]: Welp. Thanks for fixing this

**Review by neekolas — APPROVED** [review]
